### ISSUE TITLE
Error when building gui applications with MinGW

### ISSUE THREAD

**Issue by muspellsson** [githwxi/ATS-Postiats-contrib#30]
There is an error when I'm trying to build some tests for GTK and SDL bindings with MinGW. At first I run "patscc -ccats $filename" from Cygwin and there is no errors nor warnings. But then, when I try to compile the *_dats.c file from MinGW, I'm getting errors that there is no uid_t and gid_t types. The error occures only when I'm trying to build samples that need GUI functionality (for example test00.dats for GTK that prints GTK version compiles perfectly).

I'm pretty new in ATS, so please forgive me, if I don't understand some important things here.

**Comment by githwxi** [comment]
Thanks for reporting it!

I myself have never used MinGW to compile the C code generated from ATS source.

Try to create a file named my_prelude.h and then
add the following lines:

typedef int uid_t;
typedef int gid_t;

Then try

mingw -D_ATS_CCOMP_PRELUDE_USER='"my_prelude.h"'

To fully address this problem, one really needs to build an ATS compilation environment for use under Windows.

**Comment by muspellsson** [comment]
Thank you, everything works now, using custom ccomp prelude.
